name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies (Frontend)
      run: |
        cd frontend
        npm install
    
    - name: Install dependencies (Backend)
      run: |
        cd backend/functions
        npm install
    
    - name: Run tests (Frontend)
      run: |
        cd frontend
        npm run test
    
    - name: Run tests (Backend)
      run: |
        cd backend/functions
        npm run test
    
    - name: Build (Frontend)
      run: |
        cd frontend
        npm run build

  deploy-dev:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Setup Firebase
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: '$'
        firebaseServiceAccount: '$'
        projectId: 
        channelId: live
    
    - name: Deploy to Firebase
      run: |
        cd backend
        firebase deploy --only hosting,functions --project 

  deploy-prod:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Setup Firebase
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: '$'
        firebaseServiceAccount: '$'
        projectId: 
        channelId: live
    
    - name: Deploy to Firebase
      run: |
        cd backend
        firebase deploy --only hosting,functions --project 
